<a href="https://colab.research.google.com/github/Prajnaa002/Applied_Machine_Learning/blob/main/AML_pandas_assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Create a Pandas Series containing the marks: 78, 85, 92, 67, 88

    Display:

	Complete Series

	Values

	Index

	Data type

	Mean

	Maximum

	Minimum

In [ ]:
import pandas as pd

In [ ]:
marks = pd.Series([78, 85, 92, 67, 88])
print(marks.values)
print(marks.index)
print(marks.dtype)
print(marks.mean())
print(marks.max())
print(marks.min())

[78 85 92 67 88]
RangeIndex(start=0, stop=5, step=1)
int64
82.0
92
67

2.Create a Series containing:


   	| Student | Marks |
	| ------- | ----: |
	| Asha    |    85 |
	| Ravi    |    78 |
	| Meena   |    92 |
	| Kiran   |    74 |
	| Arun    |    88 |
	Display the marks of Meena.

In [ ]:
marks = pd.Series({'Asha': 85, 'Ravi': 78, 'Meena': 92, 'Kiran': 74, 'Arun': 88})
print(marks)
print(marks['Meena'])

Asha     85
Ravi     78
Meena    92
Kiran    74
Arun     88
dtype: int64
92

3. Create the following DataFrame:

| Name  | Age | Department | Marks |
| ----- | --: | ---------- | ----: |
| Asha  |  22 | CSE        |    85 |
| Ravi  |  23 | ECE        |    78 |
| Meena |  21 | CSE        |    92 |
| Kiran |  24 | ME         |    74 |
| Arun  |  22 | ECE        |    88 |

Display:

	Complete DataFrame
	First 3 rows
	Last 2 rows
	Shape
	Column names
	Data types

In [ ]:
data = {
    'Name': ['Asha', 'Ravi', 'Meena', 'Kiran', 'Arun'],
    'Age': [22, 23, 21, 24, 22],
    'Department': ['CSE', 'ECE', 'CSE', 'ME', 'ECE'],
    'Marks': [85, 78, 92, 74, 88]
}
df = pd.DataFrame(data)

print('Complete DataFrame:')
display(df)

print('\nFirst 3 rows:')
display(df.head(3))

print('\nLast 2 rows:')
display(df.tail(2))

print('\nShape:')
print(df.shape)

print('\nColumn names:')
print(df.columns)

print('\nData types:')
print(df.dtypes)

Complete DataFrame:

    Name  Age Department  Marks
0   Asha   22        CSE     85
1   Ravi   23        ECE     78
2  Meena   21        CSE     92
3  Kiran   24         ME     74
4   Arun   22        ECE     88

First 3 rows:

    Name  Age Department  Marks
0   Asha   22        CSE     85
1   Ravi   23        ECE     78
2  Meena   21        CSE     92

Last 2 rows:

    Name  Age Department  Marks
3  Kiran   24         ME     74
4   Arun   22        ECE     88

Shape:
(5, 4)

Column names:
Index(['Name', 'Age', 'Department', 'Marks'], dtype='object')

Data types:
Name          object
Age            int64
Department    object
Marks          int64
dtype: object

4. Using the previous DataFrame, display:

	info()

	describe()

	Number of rows

	Number of columns

In [ ]:
print(df.info)
print(df.describe)
print('\nNumber of rows:', df.shape[0])
print('Number of columns:', df.shape[1])

<bound method DataFrame.info of     Name  Age Department  Marks
0   Asha   22        CSE     85
1   Ravi   23        ECE     78
2  Meena   21        CSE     92
3  Kiran   24         ME     74
4   Arun   22        ECE     88>
<bound method NDFrame.describe of     Name  Age Department  Marks
0   Asha   22        CSE     85
1   Ravi   23        ECE     78
2  Meena   21        CSE     92
3  Kiran   24         ME     74
4   Arun   22        ECE     88>

Number of rows: 5
Number of columns: 4

5. Using df, display:

	Name column

	Marks column

	Name and Marks together

In [ ]:
print(df[['Name']])

    Name
0   Asha
1   Ravi
2  Meena
3  Kiran
4   Arun

In [ ]:
print(df[['Marks']])

   Marks
0     85
1     78
2     92
3     74
4     88

In [ ]:
print(df[['Name', 'Marks']])

    Name  Marks
0   Asha     85
1   Ravi     78
2  Meena     92
3  Kiran     74
4   Arun     88

6. Display:

	First row using iloc

	Third row using iloc

	Rows 1 to 3

	Name and Marks columns using loc

In [ ]:
# Display First row using iloc
print("\nFirst row (iloc[0]):\n", df.iloc[0])

# Display Third row using iloc
print("\nThird row (iloc[2]):\n", df.iloc[2])

# Display Rows 1 to 3 (inclusive, i.e., index 1, 2, 3) using iloc
print("\nRows 1 to 3 (iloc[1:4]):\n", df.iloc[1:4])

# Display Name and Marks columns using loc
print("\nName and Marks columns (loc[:, ['Name', 'Marks']]):\n", df.loc[:, ['Name', 'Marks']])

First row (iloc[0]):
 Name          Asha
Age             22
Department     CSE
Marks           85
Name: 0, dtype: object

Third row (iloc[2]):
 Name          Meena
Age              21
Department      CSE
Marks            92
Name: 2, dtype: object

Rows 1 to 3 (iloc[1:4]):
     Name  Age Department  Marks
1   Ravi   23        ECE     78
2  Meena   21        CSE     92
3  Kiran   24         ME     74

Name and Marks columns (loc[:, ['Name', 'Marks']]):
     Name  Marks
0   Asha     85
1   Ravi     78
2  Meena     92
3  Kiran     74
4   Arun     88

7. Find:

Students scoring above 80.

Students scoring between 75 and 90.

Students belonging to CSE.

CSE students scoring above 80.

In [ ]:
# Students scoring above 80
students_above_80 = df[df['Marks'] > 80]
print("\nStudents scoring above 80:\n", students_above_80)

# Students scoring between 75 and 90 (inclusive for 75 and 90)
students_between_75_and_90 = df[(df['Marks'] >= 75) & (df['Marks'] <= 90)]
print("\nStudents scoring between 75 and 90:\n", students_between_75_and_90)

# Students belonging to CSE
students_cse = df[df['Department'] == 'CSE']
print("\nStudents belonging to CSE:\n", students_cse)

# CSE students scoring above 80
cse_students_above_80 = df[(df['Department'] == 'CSE') & (df['Marks'] > 80)]
print("\nCSE students scoring above 80:\n", cse_students_above_80)

Students scoring above 80:
     Name  Age Department  Marks
0   Asha   22        CSE     85
2  Meena   21        CSE     92
4   Arun   22        ECE     88

Students scoring between 75 and 90:
    Name  Age Department  Marks
0  Asha   22        CSE     85
1  Ravi   23        ECE     78
4  Arun   22        ECE     88

Students belonging to CSE:
     Name  Age Department  Marks
0   Asha   22        CSE     85
2  Meena   21        CSE     92

CSE students scoring above 80:
     Name  Age Department  Marks
0   Asha   22        CSE     85
2  Meena   21        CSE     92

8. Display students belonging to either CSE or ECE.

In [ ]:
students_cse_ece = df[(df['Department'] == 'CSE') | (df['Department'] == 'ECE')]
print("\nStudents belonging to either CSE or ECE:\n", students_cse_ece)

Students belonging to either CSE or ECE:
     Name  Age Department  Marks
0   Asha   22        CSE     85
1   Ravi   23        ECE     78
2  Meena   21        CSE     92
4   Arun   22        ECE     88



9. Add a new column called Result.
Students scoring 75 or above should receive "Pass", otherwise "Fail".

In [ ]:
import numpy as np

df['Result'] = np.where(df['Marks'] >= 75, 'Pass', 'Fail')
print("\nDataFrame with 'Result' column:\n", df)

DataFrame with 'Result' column:
     Name  Age Department  Marks Result
0   Asha   22        CSE     85   Pass
1   Ravi   23        ECE     78   Pass
2  Meena   21        CSE     92   Pass
3  Kiran   24         ME     74   Fail
4   Arun   22        ECE     88   Pass

10. Assign grades according to:

	| Marks | Grade |
	| ----: | ----- |
	|  ≥ 90 | A     |
	|  ≥ 80 | B     |
	|  ≥ 70 | C     |
	|  < 70 | D     |

In [ ]:
import numpy as np

conditions = [
    (df['Marks'] >= 90),
    (df['Marks'] >= 80),
    (df['Marks'] >= 70),
    (df['Marks'] < 70)
]
choices = ['A', 'B', 'C', 'D']

df['Grade'] = np.select(conditions, choices, default='D') # Default can be anything, as <70 covers all remaining
print("\nDataFrame with 'Grade' column:\n", df)

DataFrame with 'Grade' column:
     Name  Age Department  Marks Result Grade
0   Asha   22        CSE     85   Pass     B
1   Ravi   23        ECE     78   Pass     C
2  Meena   21        CSE     92   Pass     A
3  Kiran   24         ME     74   Fail     C
4   Arun   22        ECE     88   Pass     B

11. Sort students:

	By marks in ascending order.

	By marks in descending order.

   By Department and then Marks.

In [ ]:
# Sort by Marks in ascending order
df_sorted_marks_asc = df.sort_values(by='Marks', ascending=True)
print("\nStudents sorted by Marks (Ascending):\n", df_sorted_marks_asc)

# Sort by Marks in descending order
df_sorted_marks_desc = df.sort_values(by='Marks', ascending=False)
print("\nStudents sorted by Marks (Descending):\n", df_sorted_marks_desc)

# Sort by Department and then by Marks
df_sorted_dept_marks = df.sort_values(by=['Department', 'Marks'], ascending=[True, True])
print("\nStudents sorted by Department and then Marks:\n", df_sorted_dept_marks)

Students sorted by Marks (Ascending):
     Name  Age Department  Marks Result Grade
3  Kiran   24         ME     74   Fail     C
1   Ravi   23        ECE     78   Pass     C
0   Asha   22        CSE     85   Pass     B
4   Arun   22        ECE     88   Pass     B
2  Meena   21        CSE     92   Pass     A

Students sorted by Marks (Descending):
     Name  Age Department  Marks Result Grade
2  Meena   21        CSE     92   Pass     A
4   Arun   22        ECE     88   Pass     B
0   Asha   22        CSE     85   Pass     B
1   Ravi   23        ECE     78   Pass     C
3  Kiran   24         ME     74   Fail     C

Students sorted by Department and then Marks:
     Name  Age Department  Marks Result Grade
0   Asha   22        CSE     85   Pass     B
2  Meena   21        CSE     92   Pass     A
1   Ravi   23        ECE     78   Pass     C
4   Arun   22        ECE     88   Pass     B
3  Kiran   24         ME     74   Fail     C

12. Consider:

data = {
    "Name": ["Asha", "Ravi", "Meena", "Kiran", "Arun"],
    "Age": [22, 23, np.nan, 24, 22],
    "Marks": [85, np.nan, 92, 74, 88]
}

students = pd.DataFrame(data)

Find:

Missing values

Number of missing values in each column

Rows containing missing values

In [ ]:
import pandas as pd
import numpy as np

data = {
    "Name": ["Asha", "Ravi", "Meena", "Kiran", "Arun"],
    "Age": [22, 23, np.nan, 24, 22],
    "Marks": [85, np.nan, 92, 74, 88]
}

students = pd.DataFrame(data)
print("Original DataFrame with missing values:\n", students)

# Find missing values
print("\nMissing values (True indicates missing):\n", students.isnull())

# Number of missing values in each column
print("\nNumber of missing values per column:\n", students.isnull().sum())

# Rows containing missing values
print("\nRows containing missing values:\n", students[students.isnull().any(axis=1)])

Original DataFrame with missing values:
     Name   Age  Marks
0   Asha  22.0   85.0
1   Ravi  23.0    NaN
2  Meena   NaN   92.0
3  Kiran  24.0   74.0
4   Arun  22.0   88.0

Missing values (True indicates missing):
     Name    Age  Marks
0  False  False  False
1  False  False   True
2  False   True  False
3  False  False  False
4  False  False  False

Number of missing values per column:
 Name     0
Age      1
Marks    1
dtype: int64

Rows containing missing values:
     Name   Age  Marks
1   Ravi  23.0    NaN
2  Meena   NaN   92.0

13. Replace:

	Missing Age with average Age
  
	Missing Marks with average Marks

In [ ]:
# Calculate average Age and Marks
average_age = students['Age'].mean()
average_marks = students['Marks'].mean()

# Replace missing Age with average Age
students['Age'].fillna(average_age, inplace=True)

# Replace missing Marks with average Marks
students['Marks'].fillna(average_marks, inplace=True)

print("DataFrame after replacing missing values with column averages:\n", students)

DataFrame after replacing missing values with column averages:
     Name    Age  Marks
0   Asha  22.00  85.00
1   Ravi  23.00  84.75
2  Meena  22.75  92.00
3  Kiran  24.00  74.00
4   Arun  22.00  88.00

/tmp/ipykernel_2731/2264420799.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  students['Age'].fillna(average_age, inplace=True)
/tmp/ipykernel_2731/2264420799.py:9: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  students['Marks'].fillna(average_marks, inplace=True)

14. Remove rows containing missing values.

In [ ]:
# Remove rows containing any missing values (if any remain, though they shouldn't after fillna)
# For demonstration, let's create a new DataFrame with some NaNs to show dropna functionality
data_with_more_nan = {
    "Name": ["Asha", "Ravi", "Meena", "Kiran", "Arun", "Priya"],
    "Age": [22, 23, np.nan, 24, 22, 25],
    "Marks": [85, np.nan, 92, 74, 88, np.nan],
    "Grade": ['A', 'B', 'A', 'C', np.nan, 'B']
}
df_temp = pd.DataFrame(data_with_more_nan)
print("Original DataFrame with more NaNs to demonstrate dropna:\n", df_temp)

df_cleaned = df_temp.dropna()
print("\nDataFrame after removing rows with any missing values:\n", df_cleaned)

Original DataFrame with more NaNs to demonstrate dropna:
     Name   Age  Marks Grade
0   Asha  22.0   85.0     A
1   Ravi  23.0    NaN     B
2  Meena   NaN   92.0     A
3  Kiran  24.0   74.0     C
4   Arun  22.0   88.0   NaN
5  Priya  25.0    NaN     B

DataFrame after removing rows with any missing values:
     Name   Age  Marks Grade
0   Asha  22.0   85.0     A
3  Kiran  24.0   74.0     C


15. Consider:

data = {
    "Name": ["Asha", "Ravi", "Meena", "Asha", "Arun"],
    "Marks": [85, 78, 92, 85, 88]
}

df2 = pd.DataFrame(data)

Find duplicates:

Display duplicate rows:

Remove duplicates:

In [ ]:
import pandas as pd

data = {
    "Name": ["Asha", "Ravi", "Meena", "Asha", "Arun"],
    "Marks": [85, 78, 92, 85, 88]
}

df2 = pd.DataFrame(data)
print("Original DataFrame:\n", df2)

# Find duplicates
duplicates = df2.duplicated()
print("\nBoolean Series indicating duplicate rows:\n", duplicates)

# Display duplicate rows
duplicate_rows = df2[df2.duplicated()]
print("\nDuplicate rows (based on all columns):\n", duplicate_rows)

# Remove duplicates
df_no_duplicates = df2.drop_duplicates()
print("\nDataFrame after removing duplicates:\n", df_no_duplicates)

Original DataFrame:
     Name  Marks
0   Asha     85
1   Ravi     78
2  Meena     92
3   Asha     85
4   Arun     88

Boolean Series indicating duplicate rows:
 0    False
1    False
2    False
3     True
4    False
dtype: bool

Duplicate rows (based on all columns):
    Name  Marks
3  Asha     85

DataFrame after removing duplicates:
     Name  Marks
0   Asha     85
1   Ravi     78
2  Meena     92
4   Arun     88

16. Given:

marks = pd.DataFrame({
    "Student": ["A", "B", "C", "D", "E"],
    "Marks": [78, 85, 92, 67, 88]
})

Calculate:

Mean

Median

Maximum

Minimum

Standard deviation

Sum

In [ ]:
import pandas as pd
import numpy as np

marks = pd.DataFrame({
    "Student": ["A", "B", "C", "D", "E"],
    "Marks": [78, 85, 92, 67, 88]
})

print("Original Marks DataFrame:\n", marks)

# Calculate statistics for the 'Marks' column
mean_marks = marks['Marks'].mean()
median_marks = marks['Marks'].median()
max_marks = marks['Marks'].max()
min_marks = marks['Marks'].min()
std_dev_marks = marks['Marks'].std()
sum_marks = marks['Marks'].sum()

print(f"\nMean Marks: {mean_marks:.2f}")
print(f"Median Marks: {median_marks:.2f}")
print(f"Maximum Marks: {max_marks}")
print(f"Minimum Marks: {min_marks}")
print(f"Standard Deviation of Marks: {std_dev_marks:.2f}")
print(f"Sum of Marks: {sum_marks}")

Original Marks DataFrame:
   Student  Marks
0       A     78
1       B     85
2       C     92
3       D     67
4       E     88

Mean Marks: 82.00
Median Marks: 85.00
Maximum Marks: 92
Minimum Marks: 67
Standard Deviation of Marks: 9.82
Sum of Marks: 410

17. Consider:

data = {
    "Name": [
        "Asha", "Ravi", "Meena",
        "Kiran", "Arun", "Divya"
    ],

    "Department": [
        "CSE", "ECE", "CSE",
        "ME", "ECE", "CSE"
    ],

    "Marks": [
        85, 78, 92,
        74, 88, 80
    ]
}

df = pd.DataFrame(data)


Find:
Average marks by department


Maximum marks by department

Number of students in each department

For each department, calculate:

Mean

Minimum

In [ ]:
import pandas as pd

data = {
    "Name": [
        "Asha", "Ravi", "Meena",
        "Kiran", "Arun", "Divya"
    ],

    "Department": [
        "CSE", "ECE", "CSE",
        "ME", "ECE", "CSE"
    ],

    "Marks": [
        85, 78, 92,
        74, 88, 80
    ]
}

df = pd.DataFrame(data)
print("Original DataFrame:\n", df)

# Average marks by department
avg_marks_by_dept = df.groupby('Department')['Marks'].mean()
print("\nAverage marks by Department:\n", avg_marks_by_dept)

# Maximum marks by department
max_marks_by_dept = df.groupby('Department')['Marks'].max()
print("\nMaximum marks by Department:\n", max_marks_by_dept)

# Number of students in each department
students_per_dept = df['Department'].value_counts()
print("\nNumber of students in each Department:\n", students_per_dept)

# For each department, calculate: Mean, Minimum, Maximum, Count
dept_stats = df.groupby('Department')['Marks'].agg(['mean', 'min', 'max', 'count'])
print("\nDepartment-wise Statistics (Mean, Min, Max, Count):\n", dept_stats)

Original DataFrame:
     Name Department  Marks
0   Asha        CSE     85
1   Ravi        ECE     78
2  Meena        CSE     92
3  Kiran         ME     74
4   Arun        ECE     88
5  Divya        CSE     80

Average marks by Department:
 Department
CSE    85.666667
ECE    83.000000
ME     74.000000
Name: Marks, dtype: float64

Maximum marks by Department:
 Department
CSE    92
ECE    88
ME     74
Name: Marks, dtype: int64

Number of students in each Department:
 Department
CSE    3
ECE    2
ME     1
Name: count, dtype: int64

Department-wise Statistics (Mean, Min, Max, Count):
                  mean  min  max  count
Department
CSE         85.666667   80   92      3
ECE         83.000000   78   88      2
ME          74.000000   74   74      1

18. Create:

students = pd.DataFrame({
    "StudentID": [101, 102, 103, 104],
    "Name": ["Asha", "Ravi", "Meena", "Kiran"]
})

marks = pd.DataFrame({
    "StudentID": [101, 102, 103, 104],
    "Marks": [85, 78, 92, 74]
})

Combine both DataFrames using StudentID.

In [ ]:
import pandas as pd

students = pd.DataFrame({
    "StudentID": [101, 102, 103, 104],
    "Name": ["Asha", "Ravi", "Meena", "Kiran"]
})

marks = pd.DataFrame({
    "StudentID": [101, 102, 103, 104],
    "Marks": [85, 78, 92, 74]
})

print("Students DataFrame:\n", students)
print("\nMarks DataFrame:\n", marks)

# Combine both DataFrames using StudentID
combined_df = pd.merge(students, marks, on='StudentID')
print("\nCombined DataFrame:\n", combined_df)

Students DataFrame:
    StudentID   Name
0        101   Asha
1        102   Ravi
2        103  Meena
3        104  Kiran

Marks DataFrame:
    StudentID  Marks
0        101     85
1        102     78
2        103     92
3        104     74

Combined DataFrame:
    StudentID   Name  Marks
0        101   Asha     85
1        102   Ravi     78
2        103  Meena     92
3        104  Kiran     74

19. Use the following dataset:

data = {
    "Name": [
        "Asha", "Ravi", "Meena",
        "Kiran", "Arun", "Divya",
        "John", "Priya"
    ],

    "Department": [
        "CSE", "ECE", "CSE",
        "ME", "ECE", "CSE",
        "ME", "ECE"
    ],

    "Attendance": [
        92, 75, 96, 68,
        82, 88, 72, 95
    ],

    "Internal": [
        85, 72, 94, 65,
        80, 86, 70, 91
    ],

    "FinalMarks": [
        88, 74, 96, 62,
        83, 89, 68, 93
    ]
}

df = pd.DataFrame(data)


Perform the following analysis:

Display the first five records.

Find the dimensions of the dataset.

Find the average final mark.

Find the highest-scoring student.

Find the lowest-scoring student.

Display students scoring above 80.

Find average marks by department.

Find students having attendance above 80%.

Sort students by FinalMarks.

Add a Result column: Pass if FinalMarks ≥ 70, otherwise Fail.

Add a performance category:

	≥90 → Excellent
	≥80 → Very Good
	≥70 → Good
	<70 → Needs Improvement

Find the department having the highest average FinalMarks.

In [ ]:
import pandas as pd
import numpy as np

data = {
    "Name": [
        "Asha", "Ravi", "Meena",
        "Kiran", "Arun", "Divya",
        "John", "Priya"
    ],

    "Department": [
        "CSE", "ECE", "CSE",
        "ME", "ECE", "CSE",
        "ME", "ECE"
    ],

    "Attendance": [
        92, 75, 96, 68,
        82, 88, 72, 95
    ],

    "Internal": [
        85, 72, 94, 65,
        80, 86, 70, 91
    ],

    "FinalMarks": [
        88, 74, 96, 62,
        83, 89, 68, 93
    ]
}

df = pd.DataFrame(data)

print("Original Student DataFrame:\n", df)

# Display the first five records.
print("\nFirst five records:\n", df.head(5))

# Find the dimensions of the dataset.
print("\nDimensions of the dataset (rows, columns):", df.shape)

# Find the average final mark.
avg_final_mark = df['FinalMarks'].mean()
print(f"\nAverage Final Mark: {avg_final_mark:.2f}")

# Find the highest-scoring student.
highest_scoring_student = df.loc[df['FinalMarks'].idxmax()]
print("\nHighest-scoring student:\n", highest_scoring_student)

# Find the lowest-scoring student.
lowest_scoring_student = df.loc[df['FinalMarks'].idxmin()]
print("\nLowest-scoring student:\n", lowest_scoring_student)

# Display students scoring above 80.
students_above_80 = df[df['FinalMarks'] > 80]
print("\nStudents scoring above 80 in FinalMarks:\n", students_above_80)

# Find average marks by department.
avg_marks_by_dept = df.groupby('Department')['FinalMarks'].mean()
print("\nAverage Final Marks by Department:\n", avg_marks_by_dept)

# Find students having attendance above 80%.
students_high_attendance = df[df['Attendance'] > 80]
print("\nStudents with Attendance above 80%:\n", students_high_attendance)

# Sort students by FinalMarks.
df_sorted_by_final_marks = df.sort_values(by='FinalMarks', ascending=False)
print("\nStudents sorted by FinalMarks (Descending):\n", df_sorted_by_final_marks)

# Add a Result column: Pass if FinalMarks ≥ 70, otherwise Fail.
df['Result'] = np.where(df['FinalMarks'] >= 70, 'Pass', 'Fail')
print("\nDataFrame with 'Result' column:\n", df)

# Add a performance category:
# ≥90 → Excellent, ≥80 → Very Good, ≥70 → Good, <70 → Needs Improvement
conditions = [
    (df['FinalMarks'] >= 90),
    (df['FinalMarks'] >= 80),
    (df['FinalMarks'] >= 70)
]
choices = ['Excellent', 'Very Good', 'Good']
df['PerformanceCategory'] = np.select(conditions, choices, default='Needs Improvement')
print("\nDataFrame with 'PerformanceCategory' column:\n", df)

# Find the department having the highest average FinalMarks.
department_highest_avg_marks = avg_marks_by_dept.idxmax()
highest_avg_marks_value = avg_marks_by_dept.max()
print(f"\nDepartment with the highest average FinalMarks: {department_highest_avg_marks} (Average: {highest_avg_marks_value:.2f})")

Original Student DataFrame:
     Name Department  Attendance  Internal  FinalMarks
0   Asha        CSE          92        85          88
1   Ravi        ECE          75        72          74
2  Meena        CSE          96        94          96
3  Kiran         ME          68        65          62
4   Arun        ECE          82        80          83
5  Divya        CSE          88        86          89
6   John         ME          72        70          68
7  Priya        ECE          95        91          93

First five records:
     Name Department  Attendance  Internal  FinalMarks
0   Asha        CSE          92        85          88
1   Ravi        ECE          75        72          74
2  Meena        CSE          96        94          96
3  Kiran         ME          68        65          62
4   Arun        ECE          82        80          83

Dimensions of the dataset (rows, columns): (8, 5)

Average Final Mark: 81.62

Highest-scoring student:
 Name          Meena
Department      CSE
Attendance       96
Internal         94
FinalMarks       96
Name: 2, dtype: object

Lowest-scoring student:
 Name          Kiran
Department       ME
Attendance       68
Internal         65
FinalMarks       62
Name: 3, dtype: object

Students scoring above 80 in FinalMarks:
     Name Department  Attendance  Internal  FinalMarks
0   Asha        CSE          92        85          88
2  Meena        CSE          96        94          96
4   Arun        ECE          82        80          83
5  Divya        CSE          88        86          89
7  Priya        ECE          95        91          93

Average Final Marks by Department:
 Department
CSE    91.000000
ECE    83.333333
ME     65.000000
Name: FinalMarks, dtype: float64

Students with Attendance above 80%:
     Name Department  Attendance  Internal  FinalMarks
0   Asha        CSE          92        85          88
2  Meena        CSE          96        94          96
4   Arun        ECE          82        80          83
5  Divya        CSE          88        86          89
7  Priya        ECE          95        91          93

Students sorted by FinalMarks (Descending):
     Name Department  Attendance  Internal  FinalMarks
2  Meena        CSE          96        94          96
7  Priya        ECE          95        91          93
5  Divya        CSE          88        86          89
0   Asha        CSE          92        85          88
4   Arun        ECE          82        80          83
1   Ravi        ECE          75        72          74
6   John         ME          72        70          68
3  Kiran         ME          68        65          62

DataFrame with 'Result' column:
     Name Department  Attendance  Internal  FinalMarks Result
0   Asha        CSE          92        85          88   Pass
1   Ravi        ECE          75        72          74   Pass
2  Meena        CSE          96        94          96   Pass
3  Kiran         ME          68        65          62   Fail
4   Arun        ECE          82        80          83   Pass
5  Divya        CSE          88        86          89   Pass
6   John         ME          72        70          68   Fail
7  Priya        ECE          95        91          93   Pass

DataFrame with 'PerformanceCategory' column:
     Name Department  Attendance  Internal  FinalMarks Result  \
0   Asha        CSE          92        85          88   Pass
1   Ravi        ECE          75        72          74   Pass
2  Meena        CSE          96        94          96   Pass
3  Kiran         ME          68        65          62   Fail
4   Arun        ECE          82        80          83   Pass
5  Divya        CSE          88        86          89   Pass
6   John         ME          72        70          68   Fail
7  Priya        ECE          95        91          93   Pass

  PerformanceCategory
0           Very Good
1                Good
2           Excellent
3   Needs Improvement
4           Very Good
5           Very Good
6   Needs Improvement
7           Excellent

Department with the highest average FinalMarks: CSE (Average: 91.00)

20. Create:

employees = pd.DataFrame({
    "Employee": [
        "E01", "E02", "E03", "E04",
        "E05", "E06", "E07", "E08"
    ],

    "Department": [
        "IT", "HR", "IT", "Finance",
        "HR", "Finance", "IT", "Finance"
    ],

    "Experience": [
        5, 3, 7, 4,
        6, 8, 2, 5
    ],

    "Salary": [
        60000, 45000, 75000, 65000,
        55000, 85000, 48000, 70000
    ]
})


Determine:

Average salary.

Maximum and minimum salary.

Employee receiving the highest salary.

Employees earning above ₹60,000.

Average salary for each department.

Average experience by department.

Number of employees in each department.

Sort employees by salary.

Find IT employees with more than 3 years of experience.

Add a SalaryLevel column:

	≥ ₹75,000 → High
	₹50,000–₹74,999 → Medium
	< ₹50,000 → Low

In [ ]:
import pandas as pd
import numpy as np

employees = pd.DataFrame({
    "Employee": [
        "E01", "E02", "E03", "E04",
        "E05", "E06", "E07", "E08"
    ],

    "Department": [
        "IT", "HR", "IT", "Finance",
        "HR", "Finance", "IT", "Finance"
    ],

    "Experience": [
        5, 3, 7, 4,
        6, 8, 2, 5
    ],

    "Salary": [
        60000, 45000, 75000, 65000,
        55000, 85000, 48000, 70000
    ]
})

print("Original Employees DataFrame:\n", employees)

# Determine Average salary.
avg_salary = employees['Salary'].mean()
print(f"\nAverage Salary: ₹{avg_salary:,.2f}")

# Maximum and minimum salary.
max_salary = employees['Salary'].max()
min_salary = employees['Salary'].min()
print(f"Maximum Salary: ₹{max_salary:,.2f}")
print(f"Minimum Salary: ₹{min_salary:,.2f}")

# Employee receiving the highest salary.
highest_paid_employee = employees.loc[employees['Salary'].idxmax()]
print("\nEmployee receiving the highest salary:\n", highest_paid_employee)

# Employees earning above ₹60,000.
employees_above_60k = employees[employees['Salary'] > 60000]
print("\nEmployees earning above ₹60,000:\n", employees_above_60k)

# Average salary for each department.
avg_salary_by_dept = employees.groupby('Department')['Salary'].mean()
print("\nAverage Salary for each Department:\n", avg_salary_by_dept)

# Average experience by department.
avg_experience_by_dept = employees.groupby('Department')['Experience'].mean()
print("\nAverage Experience by Department:\n", avg_experience_by_dept)

# Number of employees in each department.
employees_per_dept = employees['Department'].value_counts()
print("\nNumber of Employees in each Department:\n", employees_per_dept)

# Sort employees by salary.
employees_sorted_by_salary = employees.sort_values(by='Salary', ascending=False)
print("\nEmployees sorted by Salary (Descending):\n", employees_sorted_by_salary)

# Find IT employees with more than 3 years of experience.
it_employees_experienced = employees[
    (employees['Department'] == 'IT') & (employees['Experience'] > 3)
]
print("\nIT Employees with more than 3 years of experience:\n", it_employees_experienced)

# Add a SalaryLevel column:
# ≥ ₹75,000 → High
# ₹50,000–₹74,999 → Medium
# < ₹50,000 → Low
conditions = [
    (employees['Salary'] >= 75000),
    (employees['Salary'] >= 50000) & (employees['Salary'] < 75000)
]
choices = ['High', 'Medium']
employees['SalaryLevel'] = np.select(conditions, choices, default='Low')
print("\nDataFrame with 'SalaryLevel' column:\n", employees)

Original Employees DataFrame:
   Employee Department  Experience  Salary
0      E01         IT           5   60000
1      E02         HR           3   45000
2      E03         IT           7   75000
3      E04    Finance           4   65000
4      E05         HR           6   55000
5      E06    Finance           8   85000
6      E07         IT           2   48000
7      E08    Finance           5   70000

Average Salary: ₹62,875.00
Maximum Salary: ₹85,000.00
Minimum Salary: ₹45,000.00

Employee receiving the highest salary:
 Employee          E06
Department    Finance
Experience          8
Salary          85000
Name: 5, dtype: object

Employees earning above ₹60,000:
   Employee Department  Experience  Salary
2      E03         IT           7   75000
3      E04    Finance           4   65000
5      E06    Finance           8   85000
7      E08    Finance           5   70000

Average Salary for each Department:
 Department
Finance    73333.333333
HR         50000.000000
IT         61000.000000
Name: Salary, dtype: float64

Average Experience by Department:
 Department
Finance    5.666667
HR         4.500000
IT         4.666667
Name: Experience, dtype: float64

Number of Employees in each Department:
 Department
IT         3
Finance    3
HR         2
Name: count, dtype: int64

Employees sorted by Salary (Descending):
   Employee Department  Experience  Salary
5      E06    Finance           8   85000
2      E03         IT           7   75000
7      E08    Finance           5   70000
3      E04    Finance           4   65000
0      E01         IT           5   60000
4      E05         HR           6   55000
6      E07         IT           2   48000
1      E02         HR           3   45000

IT Employees with more than 3 years of experience:
   Employee Department  Experience  Salary
0      E01         IT           5   60000
2      E03         IT           7   75000

DataFrame with 'SalaryLevel' column:
   Employee Department  Experience  Salary SalaryLevel
0      E01         IT           5   60000      Medium
1      E02         HR           3   45000         Low
2      E03         IT           7   75000        High
3      E04    Finance           4   65000      Medium
4      E05         HR           6   55000      Medium
5      E06    Finance           8   85000        High
6      E07         IT           2   48000         Low
7      E08    Finance           5   70000      Medium